import { type TextStyle, type ViewStyle } from 'react-native';
import type { MarkdownStyle } from './markdown';

export const colors = {
  accent_blue: '#005FFF',
  accent_dark_blue: '#005DFF',
  accent_error: '#FF3842',
  accent_green: '#20E070',
  accent_info: '#1FE06F',
  accent_red: '#FF3742',
  bg_gradient_end: '#F7F7F7',
  bg_gradient_start: '#FCFCFC',
  bg_user: '#F7F7F8',
  black: '#000000',
  blue_alice: '#E9F2FF',
  border: '#00000014',
  code_block: '#DDDDDD',
  disabled: '#B4BBBA',
  grey: '#7A7A7A',
  grey_dark: '#72767E',
  grey_gainsboro: '#DBDBDB',
  grey_whisper: '#ECEBEB',
  icon_background: '#FFFFFF',
  label_bg_transparent: '#00000033',
  light_blue: '#E0F0FF',
  light_gray: '#E9EAED',
  modal_shadow: '#00000099',
  overlay: '#000000CC',
  shadow_icon: '#00000040',
  static_black: '#000000',
  static_white: '#ffffff',
  targetedMessageBackground: '#FBF4DD',
  text_high_emphasis: '#080707',
  text_low_emphasis: '#7E828B',
  transparent: 'transparent',
  white: '#FFFFFF',
  white_smoke: '#F2F2F2',
  white_snow: '#FCFCFC',
};

export type Theme = {
  markdown: MarkdownStyle;
  // Index signature for additional dynamic properties
  // [component: string]: any;
};

export const defaultTheme: Theme = {
  markdown: {
    autolink: {},
    blockQuoteSection: {},
    blockQuoteSectionBar: {},
    blockQuoteText: {},
    strong: {},
    codeBlock: {},
    codeBlockWrapper: {},
    codeBlockContainer: {},
    codeBlockHeaderContainer: {},
    codeBlockHeaderTitle: {},
    em: {},
    heading: {},
    heading1: {},
    heading2: {},
    heading3: {},
    heading4: {},
    heading5: {},
    heading6: {},
    hr: {},
    inlineCode: {},
    br: {},
    list: {},
    listItem: {},
    listItemBullet: {},
    listItemNumber: {},
    listItemText: {},
    listRow: {},
    sublist: {},
    url: {},
    noMargin: {},
    paragraph: {},
    paragraphCenter: {},
    del: {},
    text: {},
    table: {},
    tableRow: {},
    tableRowCell: {},
    tableHeader: {},
    tableHeaderCell: {},
  },
};
