import type {ImageStyle, TextStyle, ViewStyle} from "react-native";

export type MarkdownStyle = Partial<{
    autolink: TextStyle;
    blockQuoteBar: ViewStyle;
    blockQuoteSection: ViewStyle;
    blockQuoteSectionBar: ViewStyle;
    blockQuoteText: TextStyle | ViewStyle;
    br: TextStyle;
    codeBlock: TextStyle;
    del: TextStyle;
    em: TextStyle;
    heading: TextStyle;
    heading1: TextStyle;
    heading2: TextStyle;
    heading3: TextStyle;
    heading4: TextStyle;
    heading5: TextStyle;
    heading6: TextStyle;
    hr: ViewStyle;
    image: ImageStyle;
    inlineCode: TextStyle;
    list: ViewStyle;
    listItem: ViewStyle;
    listItemBullet: TextStyle;
    listItemNumber: TextStyle;
    listItemText: TextStyle;
    listRow: ViewStyle;
    mailTo: TextStyle;
    mentions: TextStyle;
    newline: TextStyle;
    noMargin: TextStyle;
    paragraph: TextStyle;
    paragraphCenter: TextStyle;
    paragraphWithImage: ViewStyle;
    strong: TextStyle;
    sublist: ViewStyle;
    table: ViewStyle;
    tableHeader: ViewStyle;
    tableHeaderCell: TextStyle;
    tableRow: ViewStyle;
    tableRowCell: TextStyle;
    tableRowLast: ViewStyle;
    text: TextStyle;
    u: TextStyle;
    view: ViewStyle;
}>;
